spring.application.name=spring-boot-project
logging.level.org.springframework = trace

payment_s.URL=https://vamsinandanbs.infinityfreeapp.com/
payment_s.UserName= devdefaultuser
payment_s.User_Key= devdefaultkey