spring.application.name=spring-boot-project
logging.level.org.springframework = info

payment-s.URL=https://vamsinandanbs.infinityfreeapp.com/
payment-s.UserName= proddefaultuser
payment-s.User_Key= proddefaultkey