spring.application.name=spring-boot-project
logging.level.org.springframework = debug
spring.profiles.active=prod

payment-s.URL=https://vamsinandanbs.infinityfreeapp.com/
payment-s.UserName= defaultuser
payment-s.User_Key= defaultkey